apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: {{ item.namespace }}
  labels:
    app: recommendation    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
